services:
  hunnoi-backend:
    container_name: hunnoi_backend
    image: premerxdr/hunnoi-backend:latest
    environment:
      TZ: Asia/Bangkok
    ports:
      - "7890:8000"
    env_file:
      - .env.staging
    volumes:
      - /root/hunnoi-backend/youtube_cookies.txt:/code/app/cookies.txt
    networks:
      - main-service
    restart: unless-stopped
networks:
  main-service:
    name: main-service
    external: true
