services:
  hunnoi-backend:
    container_name: hunnoi_backend
    image: premerxdr/hunnoi-backend:latest
    environment:
      TZ: Asia/Bangkok
    ports:
      - "7890:8000"
    env_file:
      - .env.staging
    networks:
      - main-service
networks:
  main-service:
