services:
  s3:
    container_name: hunnoi_minio
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - hunnoi_s3_data:/data
volumes:
  hunnoi_s3_data:
    name: s3_of_hunnoi
